# SPDX-FileCopyrightText: 2025 Nikos Tsakiridis <tsakirin@auth.gr>
#
# SPDX-License-Identifier: GPL-3.0-or-later

repos:
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    - id: docformatter
      args: [
        "--recursive",
        "--in-place",
        "--blank",
        "--wrap-summaries", "88",
        "--wrap-descriptions", "80",
        "."
      ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    - id: pyupgrade
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    - id: black
-   repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
    - id: flake8
      args: ["--max-line-length=88", "--extend-ignore=E203,E731"]
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    - id: pydocstyle
      args: ["--convention=numpy", "--add-ignore=D105"]
      files: ^spectraxai/
-   repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file